version: "{build}"

image: Visual Studio 2019

cache:
 - C:\gopath\pkg\mod -> go.sum
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml

clone_folder: C:\gopath\src\github.com\influxdata\jaeger-influxdb

environment:
  GOPATH: C:\gopath

stack: go 1.14

platform: x64

install:
  - choco install make
  - cd "%GOPATH%\src\github.com\influxdata\jaeger-influxdb"
  - git config --system core.longpaths true
  - go version
  - go env

build_script:
  - set GOOS=linux
  - set GO111MODULE=on
  - go run ./cmd/jaeger-influxdb

artifacts:
  - path: '**\jaeger-influxdb'
    name: jaeger plugin for influxdb
