version: "{build}"

image: Visual Studio 2019

cache:
 - C:\gopath\pkg\mod -> go.sum
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml

clone_folder: C:\gopath\src\github.com\influxdata\jaeger-influxdb

environment:
  GOPATH: C:\gopath

stack: go 1.14

platform: x64

install:
  - choco install make
  - cd C:\go\pkg\tool
  - mkdir linux_amd64
  - cd "%GOPATH%\src\github.com\influxdata\jaeger-influxdb"
  - git config --system core.longpaths true
  - go version

build_script:
  - set GOOS=linux
  - set CGO_ENABLED=0
  - set GO111MODULE=on
  - set GOTOOLDIR=C:\go\pkg\tool\linux_amd64
  - go env
  - go tool dist install -v pkg/tool/linux_amd64
  - go install -v -a std
  - make build

artifacts:
  - path: '**\jaeger-influxdb-linux'
    name: jaeger plugin for influxdb
